version: "3"

services:
  calibre-web:
    image: linuxserver/calibre-web
    container_name: dms.calibre-web
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    volumes:
      - ./data/calibre/config:/config
      - books:/books
    ports:
      - 8083:8083
    restart: unless-stopped
    networks:
      - web
  cloudflare-ddns:
    image: oznu/cloudflare-ddns
    container_name: dms.cloudflare-ddns
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - EMAIL=djparadyme@gmail.com
      - API_KEY=${CLOUDFLARE_API_KEY}
      - ZONE=nicholasjay.com
      - SUBDOMAIN=dms
      - PROXIED=false
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - web
  lazylibrarian:
    image: linuxserver/lazylibrarian
    container_name: dms.lazylibrarian
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    volumes:
      - ./data/lazylibrarian/config:/config
      - downloads:/downloads
      - books:/books
      - audiobooks:/audiobooks
      - magazines:/magazines
      - comics:/comics
    ports:
      - 5299:5299
    restart: unless-stopped
    networks:
      - web
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: dms.letsencrypt
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - URL=dms.nicholasjay.com
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
      - EMAIL=djparadyme@gmail.com
    volumes:
      - ./data/letsencrypt/config:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
    networks:
      - web
  lidarr:
    image: linuxserver/lidarr
    container_name: dms.lidarr
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022
    volumes:
      - ./data/lidarr/config:/config
      - music:/music
      - downloads:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped
    networks:
      - web
  ombi:
    image: linuxserver/ombi
    container_name: dms.ombi
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./data/ombi:/config
    ports:
      - 3579:3579
    restart: unless-stopped
    networks:
      - web
  tautulli:
    image: linuxserver/tautulli
    container_name: dms.tautulli
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    env_file:
      - .env
    volumes:
      - ./data/tautulli:/config
      - /c/Users/djpar/AppData/Local/Plex Media Server/Logs:/logs:ro
    ports:
      - 8181:8181
    restart: unless-stopped
    networks:
      - web
  transmission:
    image: haugene/transmission-openvpn:latest
    container_name: dms.transmission
    cap_add:
      - NET_ADMIN
    dns:
      - 1.1.1.1
      - 1.0.0.1
    env_file:
      - .env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - TRANSMISSION_ALT_SPEED_DOWN=2048
      - TRANSMISSION_ALT_SPEED_ENABLED=false
      - TRANSMISSION_ALT_SPEED_TIME_BEGIN=540
      - TRANSMISSION_ALT_SPEED_TIME_DAY=62
      - TRANSMISSION_ALT_SPEED_TIME_ENABLED=true
      - TRANSMISSION_ALT_SPEED_TIME_END=1020
      - TRANSMISSION_DOWNLOAD_QUEUE_ENABLED=true
      - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=3
      - TRANSMISSION_SPEED_LIMIT_UP=0
      - TRANSMISSION_SPEED_LIMIT_UP_ENABLED=true
      - TRANSMISSION_RATIO_LIMIT=0
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - CREATE_TUN_DEVICE=true
      - LOCAL_NETWORK=10.0.0.0/16
      - TRANSMISSION_WEB_UI=combustion
    volumes:
      - ./data/transmission:/data
      - downloads:/downloads
    ports:
      - 9091:9091
    restart: unless-stopped
    networks:
      - web

networks:
  web:

volumes:
  downloads:
    driver_opts:
      type: none
      device: /g/Downloads
      o: bind
  music:
    driver_opts:
      type: none
      device: /g/Media/Music
      o: bind
  books:
    driver_opts:
      type: none
      device: /g/Media/Books
      o: bind
  audiobooks:
    driver_opts:
      type: none
      device: /g/Media/Audiobooks
      o: bind
  magazines:
    driver_opts:
      type: none
      device: /g/Media/Magazines
      o: bind
  comics:
    driver_opts:
      type: none
      device: /g/Media/Comics
      o: bind
