version: '3'

services:
  transmission:
    image: haugene/transmission-openvpn:1.21
    container_name: dms.transmission
    privileged: true
    restart: always
    dns:
      - 8.8.8.8
      - 8.8.4.4
    env_file:
      - .env
    environment:
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - TRANSMISSION_ALT_SPEED_DOWN=500
      - TRANSMISSION_ALT_SPEED_ENABLED=false
      - TRANSMISSION_ALT_SPEED_TIME_BEGIN=540
      - TRANSMISSION_ALT_SPEED_TIME_DAY=62
      - TRANSMISSION_ALT_SPEED_TIME_ENABLED=true
      - TRANSMISSION_ALT_SPEED_TIME_END=1020
      - TRANSMISSION_SPEED_LIMIT_UP=0
      - TRANSMISSION_SPEED_LIMIT_UP_ENABLED=true
      - TRANSMISSION_RATIO_LIMIT=0
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
    ports:
      - 9091:9091
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/transmission:/data
    networks:
      - web
  tautulli:
    image: shiggins8/tautulli:latest
    container_name: dms.tautulli
    privileged: true
    restart: always
    env_file:
      - .env
    ports:
      - 8181:8181
    volumes:
      - ./data/tautulli:/config
      - /c/Users/djpar/AppData/Local/Plex Media Server/Logs:/logs:ro
    networks:
      - web
networks:
  web: