version: '3'

services:
  transmission:
    image: haugene/transmission-openvpn
    container_name: dms.transmission
    privileged: true
    restart: always
    dns:
      - 8.8.8.8
      - 8.8.4.4
    env_file:
      - .env
    environment:
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - TRANSMISSION_ALT_SPEED-DOWN=500
      - TRANSMISSION_ALT_SPEED-ENABLED=false
      - TRANSMISSION_ALT_SPEED-TIME-BEGIN=540
      - TRANSMISSION_ALT_SPEED-TIME-DAY=62
      - TRANSMISSION_ALT_SPEED-TIME-ENABLED=true
      - TRANSMISSION_ALT_SPEED-TIME-END=1020
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
    ports:
      - 9091:9091
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/transmission:/data
    networks:
      - web
  jackett:
    image: linuxserver/jackett:latest
    container_name: dms.jackett
    restart: always
    env_file:
      - .env
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
    ports:
      - 9117:9117
    volumes:
      - ./data/jackett/config/:/config
      - ./data/transmission/downloads/:/downloads
    networks:
      - web
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: dms.sonarr
    restart: always
    env_file:
      - .env
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
    ports:
      - 8989:8989
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dev/rtc:/dev/rtc:ro
      - ${TV_SHOWS_FOLDER}:/tv
      - ./data/sonarr/config:/config
      - ./data/transmission/downloads/:/downloads
    depends_on:
      - transmission
    networks:
      - web
  radarr:
    image: linuxserver/radarr:latest
    container_name: dms.radarr
    restart: always
    env_file:
      - .env
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
    ports:
      - 7878:7878
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dev/rtc:/dev/rtc:ro
      - ${MOVIES_FOLDER}:/movies
      - ./data/radarr/config:/config
      - ./data/transmission/downloads/:/downloads
    depends_on:
      - transmission
    networks:
      - web
  plex:
    image: plexinc/pms-docker:latest
    container_name: dms.plex
    restart: always
    env_file:
      - .env
    environment:
      # Once the reverse proxy is setup, we can use this
      # - ADVERTISE_IP="https://plex.${DOMAIN_NAME}/"
      - PLEX_UID=${USER_ID}
      - PLEX_GID=${GROUP_ID}
    ports:
      - 32400:32400
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MOVIES_FOLDER}:/data/movies
      - ${TV_SHOWS_FOLDER}:/data/tvshows
      - ./data/plex/config/:/config
      - /tmp/transcode/:/transcode
    depends_on:
      - transmission
      - sonarr
      - radarr
    networks:
      - web
  plexpy:
    image: linuxserver/plexpy:latest
    container_name: dms.plexpy
    restart: always
    env_file:
      - .env
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
    ports:
      - 8181:8181
    volumes:
      - ./data/plexpy:/config
      # Note: This might be different based on OS
      - ./data/plex/config/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs:ro
    depends_on:
      - plex
    networks:
      - web
networks:
  web: